import os, json, shutil, tempfile
from pathlib import Path

env = {l.split("=",1)[0]: l.split("=",1)[1] for l in Path(".env").read_text(encoding="utf-8").splitlines() if l and "=" in l and not l.startswith("#")}
for k,v in env.items():
    if k.startswith("KAGGLE"): os.environ[k] = v

import kaggle
api = kaggle.KaggleApi(); api.authenticate()

CORPUS = Path("competitions/nvidia-nemotron-model-reasoning-challenge/data/corpus/v5_local/corpus.jsonl")
USER = env["KAGGLE_USERNAME"]
SLUG = "nemotron-cot-corpus-v5"

with tempfile.TemporaryDirectory() as td:
    td = Path(td)
    shutil.copy(CORPUS, td / "corpus.jsonl")
    (td / "dataset-metadata.json").write_text(json.dumps({
        "title": "Nemotron CoT Corpus v5 (1029 rows, verified CoT)",
        "id": f"{USER}/{SLUG}",
        "licenses": [{"name": "CC0-1.0"}],
        "subtitle": "Deterministic CoT, gravity + unit_conversion only",
        "description": "1029 verified-CoT rows: 529 gravity + 500 unit_conversion. Generated by deterministic solvers.",
        "keywords": ["nemotron", "reasoning"],
    }, indent=2), encoding="utf-8")

    try:
        r = api.dataset_create_new(folder=str(td), public=False, quiet=False)
        print("create:", r)
    except Exception as e:
        print(f"create err (trying version): {e}")
        r = api.dataset_create_version(folder=str(td), version_notes="v5 with verified CoT", quiet=False)
        print("version:", r)

print(f"\nattach: '{USER}/{SLUG}'")
